name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: mvn test

  coverage:
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Generate JaCoCo Report
        run: mvn jacoco:report
